```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: CI
  displayName: "Continuous Integration"

  jobs:
  - job: BuildJob
    displayName: "Build Application"

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet restore
      displayName: "Restore Dependencies"

    - script: dotnet build --configuration Release
      displayName: "Build Project"

- stage: Testing
  displayName: "Testing Stage"

  dependsOn: CI

  jobs:
  - job: TestJob
    displayName: "Run Unit Tests"

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet test --configuration Release
      displayName: "Execute Tests"

- stage: Delivery
  displayName: "Delivery Stage"

  dependsOn: Testing

  jobs:
  - job: DeliveryJob
    displayName: "Publish Application"

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
      displayName: "Publish Project"

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'CalculadoraApp'

```
