# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

```yaml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# =========================
# STAGE 1 - CI
# =========================
- stage: CI
  displayName: "Continuous Integration"

  jobs:
  - job: BuildJob
    displayName: "Build Application"

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet restore
      displayName: "Restore Dependencies"

    - script: dotnet build --configuration Release
      displayName: "Build Project"

# =========================
# STAGE 2 - TESTING
# =========================
- stage: Testing
  displayName: "Run Unit Tests"

  dependsOn: CI

  jobs:
  - job: TestJob
    displayName: "Execute Tests"

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet test --configuration Release --logger trx
      displayName: "Run Unit Tests"

# =========================
# STAGE 3 - DELIVERY
# =========================
- stage: Delivery
  displayName: "Publish Application"

  dependsOn: Testing

  jobs:
  - job: DeliveryJob
    displayName: "Publish Artifacts"

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '10.x'

    - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
      displayName: "Publish Application"

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'CalculadoraApp'
      displayName: "Upload Artifact"
```

